"""Spanish requirement texts and hints, generated from content/fmse/i18n/es by
scripts/fmse/sync_labkit_translations.py. Do not edit by hand."""

from .i18n import add_catalog

add_catalog({
    'All required task-brief sections exist': 'Existen todas las secciones obligatorias del brief',
    'Re-read the list of sections in the challenge brief. A brief that skips uncertainty handling or the output interface leaves the model to guess them.': 'Vuelve a leer la lista de secciones del enunciado. Un brief que omite la gestión de la incertidumbre o la interfaz de salida deja que el modelo las adivine.',
    'Success criteria are measurable or inspectable': 'Los criterios de éxito se pueden medir o inspeccionar',
    'Ask how a reviewer would decide pass or fail. A criterion needs a threshold, count, or a concrete property someone can check.': 'Pregúntate cómo decidiría un revisor si pasa o falla. Un criterio necesita un umbral, un recuento o una propiedad concreta que alguien pueda comprobar.',
    'Evidence sources are distinguished from assumptions': 'Las fuentes de evidencia se distinguen de los supuestos',
    'Separate what you know from a named source from what you are assuming. The two need different treatment when they turn out to be wrong.': 'Separa lo que sabes por una fuente con nombre de lo que estás suponiendo. Cuando resultan estar equivocados, hay que tratarlos de forma distinta.',
    'No instruction requests private/hidden reasoning': 'Ninguna instrucción pide razonamiento privado u oculto',
    "Ask for concise rationale, assumptions, and checks that can be inspected - not for the model's private reasoning.": 'Pide una justificación breve, los supuestos y comprobaciones que se puedan inspeccionar, no el razonamiento privado del modelo.',
    'Valid response passes': 'Una respuesta válida pasa',
    'Start from the happy path: a response that parses and satisfies the schema and the business rule should come back as a success with the parsed data.': 'Empieza por el camino feliz: una respuesta que se puede parsear y que cumple el esquema y la regla de negocio debe volver como éxito, con los datos ya parseados.',
    'Malformed JSON fails gracefully': 'Un JSON mal formado falla de forma controlada',
    'Parsing untrusted text can raise. Decide which result status represents that, and return it instead of letting the exception escape.': 'Parsear texto que no es de fiar puede lanzar una excepción. Decide qué estado del resultado representa ese caso y devuélvelo, en lugar de dejar que la excepción se escape.',
    'Schema mismatch returns typed error': 'Si no se cumple el esquema, se devuelve un error tipado',
    'Valid JSON is not the same as a valid contract. Report schema violations as their own typed status, separate from parse failures.': 'Que el JSON sea válido no significa que el contrato lo sea. Informa de los incumplimientos del esquema con su propio estado tipado, separado de los fallos de parseo.',
    'Retry count is bounded': 'El número de reintentos está acotado',
    'Every retry costs time and money. Count attempts and stop at the configured bound, whatever the endpoint keeps returning.': 'Cada reintento cuesta tiempo y dinero. Cuenta los intentos y detente en el límite configurado, sin importar lo que el endpoint siga devolviendo.',
    'Business-rule violation returns typed error': 'Si se incumple una regla de negocio, se devuelve un error tipado',
    'A schema cannot check arithmetic. Apply the deterministic business rule after schema validation and report its failure as its own status.': 'Un esquema no puede comprobar la aritmética. Aplica la regla de negocio determinista después de validar el esquema e informa de su fallo con un estado propio.',
    'Secret is not printed or persisted in notebook output': 'El secreto no se imprime ni queda guardado en la salida del notebook',
    'Look at everything your function prints, logs, raises, or returns. None of it may contain the credential value.': 'Revisa todo lo que tu función imprime, registra, lanza o devuelve. Nada de eso puede contener el valor de la credencial.',
    'Experiment manifest exported': 'Se exporta el manifiesto del experimento',
    'Revisit lesson 1.4: the manifest records model, prompt version, dataset version, and metrics.': 'Vuelve a la lección 1.4: el manifiesto registra el modelo, la versión del prompt, la versión del conjunto de datos y las métricas.',
    'Problem statement does not prescribe a solution': 'El enunciado del problema no prescribe ninguna solución',
    'Describe the operational pain and the decision it affects. If the statement names an agent, a chatbot, RAG, or a model, it is describing a solution.': 'Describe el problema operativo y la decisión a la que afecta. Si el enunciado menciona un agente, un chatbot, RAG o un modelo, está describiendo una solución.',
    'At least 3 stakeholder groups': 'Hay al menos 3 grupos de partes interesadas',
    'Think beyond the requester: who is affected, who operates it, who must approve, who audits it?': 'Mira más allá de quien hace la solicitud: ¿a quién afecta, quién lo opera, quién tiene que aprobarlo, quién lo audita?',
    'Nominal + exception + degraded scenario included': 'Incluye un escenario nominal, uno de excepción y uno degradado',
    'What happens when a dependency is unavailable or confidence is low? That is the degraded mode, and it is different from an exception.': '¿Qué pasa cuando una dependencia no está disponible o la confianza es baja? Eso es el modo degradado, y no es lo mismo que una excepción.',
    'At least 3 measurable MOEs': 'Hay al menos 3 MOE medibles',
    'An MOE needs a stakeholder outcome, a metric, and a target someone could observe in realistic use.': 'Una MOE necesita un resultado para las partes interesadas, una métrica y un objetivo que alguien pueda observar en un uso realista.',
    'Non-goals explicitly stated': 'Los objetivos que quedan fuera están indicados de forma explícita',
    'Say what the system will deliberately not do. Non-goals bound the scope as much as goals do.': 'Di qué es lo que el sistema no va a hacer, a propósito. Los objetivos que quedan fuera acotan el alcance tanto como los objetivos.',
    'Every requirement has ID, statement, rationale, verification method': 'Cada requisito tiene ID, enunciado, justificación y método de verificación',
    "A requirement nobody can verify is a wish. Each needs a 'shall' statement, a reason it exists, and how you will prove it (test, analysis, inspection or demonstration).": 'Un requisito que nadie puede verificar es un deseo. Cada uno necesita una frase con "deberá", el motivo por el que existe y cómo vas a demostrar que se cumple (prueba, análisis, inspección o demostración).',
    'No duplicate IDs': 'No hay IDs duplicados',
    'Traceability breaks the moment two items share an identifier. IDs must be unique across requirements and across failure modes.': 'La trazabilidad se rompe en cuanto dos elementos comparten identificador. Los IDs tienen que ser únicos entre los requisitos y entre los modos de fallo.',
    'At least one requirement in each required category': 'Hay al menos un requisito en cada categoría obligatoria',
    'Revisit lesson 3.2: functional behaviour is only one category. Look for performance, interface, security, cost and operational obligations too.': 'Vuelve a la lección 3.2: el comportamiento funcional es solo una categoría. Busca también obligaciones de rendimiento, de interfaz, de seguridad, de costo y operativas.',
    'RPN arithmetic correct': 'La aritmética del RPN es correcta',
    'RPN is Severity x Occurrence x Detection, each on a 1-10 scale. Recompute every row rather than estimating the product.': 'El RPN es Gravedad x Ocurrencia x Detección, cada una de 1 a 10. Vuelve a calcular cada fila en lugar de estimar el producto.',
    'Every high-severity failure has at least one mitigation and verification link': 'Cada fallo de gravedad alta tiene al menos una mitigación y un enlace a su verificación',
    'For each failure with severity 8 or more: which control reduces it, and which requirement proves that control works?': 'Para cada fallo con gravedad 8 o más: ¿qué control lo reduce y qué requisito demuestra que ese control funciona?',
    'At least 12 requirements and 10 failure modes, including indirect prompt injection and excessive agency': 'Al menos 12 requisitos y 10 modos de fallo, incluidos la inyección indirecta de prompts y la agencia excesiva',
    'The assistant reads documents it did not write and can trigger payments. Which failure modes does that create?': 'El asistente lee documentos que no escribió y puede disparar pagos. ¿Qué modos de fallo abre eso?',
    'Benchmark contains >=20 samples': 'El benchmark contiene >=20 muestras',
    'A handful of tasks cannot separate two configurations from noise. Use at least 20, drawn from the task pool.': 'Con un puñado de tareas no se distinguen dos configuraciones del ruido. Usa al menos 20, tomadas del conjunto de tareas.',
    'At least 2 model/config variants compared': 'Se comparan al menos 2 variantes de modelo o de configuración',
    'A characterization compares alternatives. Configure at least two distinct variants (model, effort or prompt style).': 'Caracterizar es comparar alternativas. Configura al menos dos variantes distintas (de modelo, de esfuerzo o de estilo de prompt).',
    'Quality metric defined': 'La métrica de calidad está definida',
    "State what 'quality' means for this scenario and how it is computed, before looking at the numbers.": "Antes de mirar los números, di qué significa 'calidad' en este escenario y cómo se calcula.",
    'Latency and cost captured': 'Se registran la latencia y el costo',
    'Every variant needs measured latency and cost next to quality - the trade-off is the point of the exercise.': 'Cada variante necesita su latencia y su costo medidos junto a la calidad; el compromiso entre los tres es justamente lo que se estudia en el ejercicio.',
    'Conclusion cites measured evidence and limitations': 'La conclusión cita evidencia medida y sus limitaciones',
    'A recommendation is conditional: under which requirements does each variant win, which measured numbers show it, and what could make this benchmark misleading?': 'Una recomendación es condicional: ¿con qué requisitos gana cada variante, qué números medidos lo demuestran y qué podría hacer que este benchmark engañe?',
    'Benchmark reproducible': 'El benchmark es reproducible',
    'Report the numbers the profiler actually produced for the configuration you submitted; anyone re-running it must get the same results.': 'Informa los números que el perfilador produjo de verdad con la configuración que entregaste; cualquiera que lo vuelva a ejecutar tiene que obtener los mismos resultados.',
    'Retrieval benchmark exists': 'Existe un benchmark de recuperación',
    'Retrieval quality is measured, not assumed: write at least 10 questions, each with the user asking it and the document ids that answer it.': 'La calidad de la recuperación se mide, no se supone: escribe al menos 10 preguntas y, para cada una, quién la hace y los ids de los documentos que la responden.',
    'Source IDs preserved end to end': 'Los IDs de las fuentes se conservan de principio a fin',
    'Every citation must be a document you actually retrieved, and every answer must say which documents support it.': 'Cada cita tiene que ser un documento que recuperaste de verdad, y cada respuesta tiene que decir qué documentos la respaldan.',
    'Unauthorized documents excluded': 'Se excluyen los documentos no autorizados',
    'Access control is enforced before retrieval results reach the context, not by asking the generator to ignore them.': 'El control de acceso se aplica antes de que los resultados de la recuperación entren en el contexto, no pidiéndole al generador que los ignore.',
    'Conflicting evidence test handled': 'Se supera la prueba de evidencia contradictoria',
    'When two versions of a policy disagree, surface both with their dates instead of silently choosing one.': 'Cuando dos versiones de una política no coinciden, muestra las dos con sus fechas en lugar de quedarte con una sin decirlo.',
    'Context budget enforced': 'Se respeta el presupuesto de contexto',
    'Measure the context you assemble. Chunking and selection, not whole documents, keep it inside the budget.': 'Mide el contexto que ensamblas. Lo que lo mantiene dentro del presupuesto es fragmentar y seleccionar, no meter documentos enteros.',
    'Grounded-answer threshold met on the held-out public set': 'Se alcanza el umbral de respuestas fundamentadas en el conjunto público reservado',
    'Separate the failure: was the right evidence retrieved (recall@3), or retrieved but not used? Fix the layer that fails.': 'Separa el fallo: ¿se recuperó la evidencia correcta (recall@3), o se recuperó pero no se usó? Arregla la capa que falla.',
    '>=3 credible alternatives': '>=3 alternativas creíbles',
    'Generate genuinely different concepts - different patterns on the autonomy spectrum - each described well enough to be evaluated.': 'Plantea conceptos de verdad distintos (patrones diferentes dentro del espectro de autonomía), cada uno descrito lo suficiente como para poder evaluarlo.',
    'Criteria trace to requirements': 'Los criterios se trazan hasta los requisitos',
    'Every criterion should exist because a requirement exists. Name the requirement ids each criterion measures.': 'Cada criterio debería existir porque existe un requisito. Indica los ids de los requisitos que mide cada criterio.',
    'Weights sum to 1': 'Los pesos suman 1',
    'Weights express operational priority as shares of one whole; normalise them.': 'Los pesos expresan la prioridad operativa como partes de un todo; normalízalos.',
    'Sensitivity analysis executed': 'Se ha hecho el análisis de sensibilidad',
    'Perturb the two highest weights by +/-20%, renormalise the rest, and recompute which alternative wins each time.': 'Altera los dos pesos más altos en +/-20%, normaliza el resto y vuelve a calcular cada vez qué alternativa gana.',
    'Decision includes reversal/revisit conditions': 'La decisión incluye condiciones para revertirla o revisarla',
    'An ADR states when it should be revisited. Write triggers someone could observe, with thresholds.': 'Un ADR dice cuándo hay que revisarlo. Escribe disparadores que alguien pueda observar, con sus umbrales.',
    'Schema interface declared': 'Se declara la interfaz del esquema',
    'The manifest must declare the output contract (a JSON Schema with the five fields), and every output must satisfy it.': 'El manifiesto tiene que declarar el contrato de salida (un JSON Schema con los cinco campos), y todas las salidas tienen que cumplirlo.',
    'Untrusted input delimited/separated': 'La entrada no fiable está delimitada o separada',
    'Separate authority-bearing instructions from document content and rerun the indirect-injection test.': 'Separa las instrucciones que tienen autoridad del contenido del documento y vuelve a ejecutar la prueba de inyección indirecta.',
    'Missing values not invented': 'No se inventan los valores ausentes',
    "When the document does not state a value, the correct output is 'unknown' (null), not a plausible guess. Say so, and check it in code.": "Si el documento no indica un valor, la salida correcta es 'desconocido' (null), no una suposición verosímil. Dilo en el prompt y compruébalo en el código.",
    'Multiple totals handled': 'Se gestionan las facturas con varios totales',
    'Invoices print several totals. State which one the interface means, and verify it deterministically where you can.': 'Las facturas imprimen varios totales. Di cuál de ellos es el que espera la interfaz y, donde puedas, verifícalo de forma determinista.',
    'Prompt version and changelog included': 'Se incluyen la versión del prompt y el registro de cambios',
    'Treat the prompt as a source artifact: a semantic version and a changelog entry per version, each change tied to evidence.': 'Trata el prompt como un artefacto fuente: una versión semántica y una entrada en el registro de cambios por cada versión, y cada cambio ligado a evidencia.',
    'Public robustness >= 80% across the adversarial invoice set': 'Robustez pública >= 80% en el conjunto de facturas adversariales',
    'Look at which case types fail (missing, totals, OCR, injection) and address the layer responsible - prompt rule or post-processing.': 'Mira qué tipos de caso fallan (valores ausentes, totales, OCR, inyección) y actúa sobre la capa responsable, ya sea una regla del prompt o el posprocesado.',
    'Schema-valid output': 'La salida es válida según el esquema',
    'Only ever return data you have validated against the contract; when validation keeps failing, return a typed escalation instead of the data.': 'Devuelve solo datos que hayas validado contra el contrato; si la validación sigue fallando, devuelve un escalado tipado en lugar de los datos.',
    'Domain validator catches semantic invalidity': 'El validador de dominio detecta los datos semánticamente inválidos',
    'Schema-valid is not the same as allowed. Check each call against the approval it claims: SKU, quantity bound, unit-price bound.': 'Que sea válido según el esquema no significa que esté permitido. Comprueba cada llamada contra la aprobación que dice tener: el SKU, el límite de cantidad y el límite de precio unitario.',
    'Tool mutability declared': 'Se declara si la herramienta modifica datos',
    'Every tool contract states whether it reads or writes, so the application (not the model) can decide what needs approval.': 'Todo contrato de herramienta dice si la herramienta lee o escribe, para que sea la aplicación (y no el modelo) la que decida qué necesita aprobación.',
    'Authorization field required for writes': 'Las escrituras exigen un campo de autorización',
    'A write must carry authorization evidence the application can check. Make it a required parameter and reject unknown approvals.': 'Una escritura tiene que llevar una evidencia de autorización que la aplicación pueda comprobar. Conviértela en un parámetro obligatorio y rechaza las aprobaciones que no conozcas.',
    'Retry loop bounded': 'El bucle de reintentos está acotado',
    'Repairing forever costs money and can still be wrong. Stop after max_attempts and escalate.': 'Reparar sin límite cuesta dinero y, aun así, el resultado puede seguir estando mal. Detente al llegar a max_attempts y escala.',
    'Required facts preserved': 'Se conservan los hechos necesarios',
    'Compaction must keep decisions, constraints, open questions and tool-state handles verbatim enough to act on. Check against the verification set.': 'La compactación tiene que conservar las decisiones, las restricciones, las preguntas abiertas y las referencias al estado de las herramientas, con la literalidad suficiente para poder actuar. Compruébalo contra el conjunto de verificación.',
    'Stale/irrelevant context removed': 'Se elimina el contexto desactualizado o irrelevante',
    'Superseded tool results and social chatter cost tokens and can mislead. Select what is still true and useful.': 'Los resultados de herramientas ya superados y la charla social cuestan tokens y pueden despistar. Quédate con lo que sigue siendo verdadero y útil.',
    'Stable vs dynamic context separated': 'El contexto estable y el dinámico están separados',
    'Stable instructions and tool definitions belong in a fixed prefix; everything that changes goes after it (this is also what makes prompt caching work).': 'Las instrucciones estables y las definiciones de las herramientas van en un prefijo fijo; todo lo que cambia va después (y eso es, además, lo que hace funcionar la caché de prompts).',
    'Context budget respected': 'Se respeta el presupuesto de contexto',
    'Measure the compacted context. It must fit the budget and be at least 40% smaller than the raw trace.': 'Mide el contexto compactado. Tiene que caber en el presupuesto y ser al menos un 40% más pequeño que la traza en bruto.',
    'Memory/state ownership documented': 'Está documentado quién es responsable de la memoria y del estado',
    'For each kind of state, say who owns it, where it lives, how long it is kept and how it is deleted. Secrets and guesses are never durable memory.': 'Para cada tipo de estado, di quién es su responsable, dónde vive, cuánto tiempo se conserva y cómo se borra. Los secretos y las suposiciones nunca son memoria duradera.',
    'Loop budget enforced': 'Se respeta el presupuesto del bucle',
    'The model proposes; the application decides when to stop. Count steps and stop at the budget, whatever the planner wants next.': 'El modelo propone; la aplicación decide cuándo parar. Cuenta los pasos y detente al llegar al presupuesto, sin importar qué quiera hacer el planificador a continuación.',
    'Read/write capability separation': 'Las capacidades de lectura y de escritura están separadas',
    'Declare, per tool, whether it reads or mutates. The policy - not the tool name or the model - decides what needs approval.': 'Declara, para cada herramienta, si lee o modifica datos. Qué necesita aprobación lo decide la política, no el nombre de la herramienta ni el modelo.',
    'Approval required for mutation': 'Toda modificación requiere aprobación',
    'Before any write reaches the server, ask the approver for that exact action and pass its token; if refused, the action must not happen.': 'Antes de que cualquier escritura llegue al servidor, pídele al aprobador permiso para esa acción exacta y pasa su token; si la rechaza, la acción no puede ocurrir.',
    'Tool errors handled': 'Se gestionan los errores de las herramientas',
    "A tool error is an observation, not a crash. Return it to the planner as a typed result and keep the loop's invariants.": 'Un error de una herramienta es una observación, no una caída del sistema. Devuélveselo al planificador como un resultado tipado y conserva las invariantes del bucle.',
    'Explicit state handle or stateless design documented': 'Hay una referencia explícita al estado o está documentado un diseño sin estado',
    'Say where state lives between calls: in an explicit handle you pass, or in your application because the protocol core is stateless.': 'Di dónde vive el estado entre llamadas: en una referencia explícita que tú pasas, o en tu aplicación, porque el núcleo del protocolo no tiene estado.',
    'Evidence provenance captured': 'Se registra la procedencia de la evidencia',
    'Record what the agent saw at each step - URL and a screenshot hash - so every action can be audited against its evidence.': 'Registra lo que vio el agente en cada paso (la URL y el hash de una captura de pantalla), para que cada acción pueda auditarse contra su evidencia.',
    'Action allowlist defined': 'Hay una lista de acciones permitidas',
    'Declare which hosts and action types are allowed, and refuse anything else - including links the page itself suggests.': 'Declara qué servidores y qué tipos de acción se permiten, y rechaza todo lo demás, incluidos los enlaces que sugiera la propia página.',
    'High-impact action approval present': 'Las acciones de alto impacto requieren aprobación',
    'Placing an order spends money. Ask the approver for this exact item and quantity before the click; if refused, stop.': 'Hacer un pedido cuesta dinero. Antes del clic, pídele al aprobador que confirme exactamente este artículo y esta cantidad; si lo rechaza, detente.',
    'Post-action verification included': 'Se verifica el resultado después de cada acción',
    "A click can succeed while the real-world state is wrong. Check the order's status page and report what it says.": 'Un clic puede salir bien y, aun así, dejar un estado real equivocado. Consulta la página de estado del pedido e informa de lo que dice.',
    'Failure/retry budget bounded': 'El presupuesto de fallos y reintentos está acotado',
    'UI automation is flaky. Retry a missing element a bounded number of times (<= 3), then fail cleanly.': 'La automatización de interfaces es inestable. Si un elemento no aparece, reintenta un número acotado de veces (<= 3) y después falla de forma limpia.',
    'Simulation passes normal + changed-layout scenarios': 'La simulación supera el escenario normal y el de maquetación cambiada',
    'Locate elements by role and visible label, not by ids that change; handle an extra confirmation step.': 'Localiza los elementos por su rol y su etiqueta visible, no por ids que cambian, y prevé un paso de confirmación adicional.',
    'Golden set categorized': 'El conjunto de referencia está categorizado',
    'Organise the golden set by capability, edge case, severity and provenance. Each item needs a category and a severity.': 'Organiza el conjunto de referencia por capacidad, caso límite, gravedad y procedencia. Cada elemento necesita una categoría y una gravedad.',
    'At least 3 scorer types': 'Hay al menos 3 tipos de evaluador',
    'Exact match alone misses whole classes of failure. Combine structural, numeric and behavioural scorers.': 'La coincidencia exacta, por sí sola, deja pasar clases enteras de fallos. Combina evaluadores estructurales, numéricos y de comportamiento.',
    'Metamorphic transformations implemented': 'Hay transformaciones metamórficas implementadas',
    'Define transformations under which the output must NOT change (reordering, padding, casing...) and use them as tests.': 'Define transformaciones ante las que la salida NO debe cambiar (reordenar, añadir relleno, cambiar mayúsculas...) y úsalas como pruebas.',
    'Verification traceability present': 'Existe trazabilidad de la verificación',
    'Every critical requirement should map to at least one test id that exists in your golden set.': 'Cada requisito crítico debería corresponderse con al menos un id de prueba que exista en tu conjunto de referencia.',
    'Validation scenario defined': 'Hay un escenario de validación definido',
    'Verification proves requirements; validation asks whether stakeholders get the intended outcome in realistic use. Describe one such scenario.': 'La verificación demuestra los requisitos; la validación pregunta si las partes interesadas consiguen el resultado previsto en un uso realista. Describe un escenario de ese tipo.',
    'Fault-detection target met': 'Se alcanza el objetivo de detección de fallos',
    'Look at which planted faults survive your suite. Each surviving mutant is a missing test: which category and which transformation would expose it?': 'Mira qué fallos introducidos sobreviven a tu conjunto. Cada mutante que sobrevive es una prueba que falta: ¿qué categoría y qué transformación lo pondrían al descubierto?',
    'At least 4 vulnerabilities documented': 'Hay al menos 4 vulnerabilidades documentadas',
    'Attack every trust boundary: retrieved content, tools that mutate, loops, rendered output, logs.': 'Ataca cada límite de confianza: el contenido recuperado, las herramientas que modifican datos, los bucles, la salida que se presenta, los registros.',
    'Each has asset/impact/control/test': 'Cada una tiene activo, impacto, control y prueba',
    'A finding is complete when it names the asset at risk, the impact, the architectural control, and the regression test that proves it.': 'Un hallazgo está completo cuando nombra el activo en riesgo, el impacto, el control de arquitectura y la prueba de regresión que lo demuestra.',
    'Mutation tools least-privileged': 'Las herramientas que modifican datos tienen el mínimo privilegio',
    'Scope each mutating tool to the minimum: which statements, which recipients, and whether a human must approve.': 'Limita cada herramienta que modifica datos al mínimo imprescindible: qué sentencias SQL, qué destinatarios y si una persona tiene que aprobar.',
    'Injection regression tests included': 'Hay pruebas de regresión contra la inyección',
    'Capture the successful injection as a reproducible test that fails on the vulnerable agent and passes on yours.': 'Captura la inyección que funcionó como una prueba reproducible: debe fallar en el agente vulnerable y pasar en el tuyo.',
    'Resource limits defined': 'Los límites de recursos están definidos',
    'Bound tool calls and output size so an attacker (or a loop) cannot consume unbounded resources.': 'Acota las llamadas a herramientas y el tamaño de la salida, para que ni un atacante ni un bucle puedan consumir recursos sin límite.',
    'Zero known high-severity planted vulnerabilities unresolved': 'Ninguna vulnerabilidad conocida de gravedad alta introducida a propósito queda sin resolver',
    'Re-run the full attack suite against your agent. Any attack that still succeeds is an open high-severity finding.': 'Vuelve a lanzar el conjunto completo de ataques contra tu agente. Cualquier ataque que siga funcionando es un hallazgo abierto de gravedad alta.',
    'Train/dev/test split present': 'Existe una división en entrenamiento, desarrollo y prueba',
    'Split once, before optimising: disjoint train (demos), dev (selection) and test (final, untouched) sets, each large enough to mean something.': 'Divide una sola vez, antes de optimizar: conjuntos disjuntos de entrenamiento (ejemplos), desarrollo (selección) y prueba (final, sin tocar), cada uno lo bastante grande como para decir algo.',
    'Baseline recorded': 'La línea base queda registrada',
    'Record the unoptimised program and its measured scores first; improvement only means something against it.': 'Registra primero el programa sin optimizar y sus puntuaciones medidas; una mejora solo tiene sentido comparada con él.',
    'Optimization log retained': 'Se conserva el registro de la optimización',
    'Keep every trial: the candidate program, the split it was scored on, its score and its cost.': 'Conserva cada intento: el programa candidato, la división con la que se puntuó, su puntuación y su costo.',
    'Held-out test not used for tuning': 'El conjunto de prueba reservado no se usa para ajustar',
    'Selection and demos must come from train/dev only. Touching the test set while tuning makes the final number meaningless.': 'La selección y los ejemplos deben salir únicamente de entrenamiento y desarrollo. Si tocas el conjunto de prueba mientras ajustas, el número final deja de significar nada.',
    'Pareto comparison produced': 'Se produce una comparación de Pareto',
    'Compare candidates on quality AND cost; mark which are dominated, and choose from the non-dominated set under the constraints.': 'Compara los candidatos por calidad Y por costo; marca cuáles están dominados y elige entre los no dominados que cumplen las restricciones.',
    'Held-out improvement with no protected-case regression': 'Mejora en datos reservados sin regresión en los casos protegidos',
    'Optimise for the scalar only if protected rows (security incidents) do not get worse and cost stays within the limit.': 'Optimiza el escalar solo si las filas protegidas (incidentes de seguridad) no empeoran y el costo se mantiene dentro del límite.',
    'Release manifest complete': 'El manifiesto de versión está completo',
    'A deployment is a configuration bundle: code, prompts, tool schemas, model/config, dataset and eval versions, and the thresholds used.': 'Un despliegue es un paquete de configuración: código, prompts, esquemas de herramientas, modelo y configuración, versiones de los datos y de las evaluaciones, y los umbrales que se usaron.',
    'High-severity eval gate blocking': 'El control de evaluación de gravedad alta bloquea',
    'An average can improve while a protected case breaks. Any failing high-severity case must block, whatever the aggregate.': 'El promedio puede mejorar mientras un caso protegido se rompe. Cualquier caso de gravedad alta que falle tiene que bloquear, diga lo que diga el agregado.',
    'Rollback criteria explicit': 'Los criterios de marcha atrás son explícitos',
    'Write the conditions that trigger rollback as metric, threshold and window - and make them executable on canary metrics.': 'Escribe las condiciones que disparan la marcha atrás como métrica, umbral y ventana, de modo que se puedan ejecutar sobre las métricas del canary.',
    'Trace schema covers model/retrieval/tool events': 'El esquema de trazas cubre los eventos del modelo, de la recuperación y de las herramientas',
    'Reconstructing a failure needs model calls, retrieval and tool calls in one trace, with ids, timing and versions.': 'Para reconstruir un fallo necesitas las llamadas al modelo, la recuperación y las llamadas a herramientas en una sola traza, con ids, tiempos y versiones.',
    'Cost and latency SLOs linked to requirements': 'Los SLO de costo y latencia están ligados a requisitos',
    'Each SLO exists because a requirement does: give its threshold and the requirement id it verifies.': 'Cada SLO existe porque existe un requisito: indica su umbral y el id del requisito que verifica.',
    'Release simulation PASS': 'La simulación de la versión PASA',
    'Run your gate on every candidate: noise within tolerance promotes; protected regressions, SLO breaches and schema failures block.': 'Ejecuta tu control sobre cada candidata: el ruido dentro de la tolerancia deja pasar; las regresiones en casos protegidos, los incumplimientos de SLO y los fallos de esquema bloquean.',
    'All critical requirements trace to verification': 'Todos los requisitos críticos se trazan hasta una verificación',
    'Every critical requirement id must appear in the traceability matrix with at least one verification (test id or method).': 'Cada id de requisito crítico tiene que aparecer en la matriz de trazabilidad con al menos una verificación (id de prueba o método).',
    'No unresolved high-severity security finding': 'Ningún hallazgo de seguridad de gravedad alta queda sin resolver',
    'An unresolved high-impact authorization or data-integrity flaw fails the capstone regardless of other scores.': 'Un fallo de autorización o de integridad de datos de alto impacto que siga sin resolver reprueba el proyecto final, sean cuales sean las demás puntuaciones.',
    'Schema/domain integrity checks pass': 'Pasan las comprobaciones de integridad del esquema y del dominio',
    'Every match and discrepancy must reference real rows, no row may be matched twice, and matched amounts must agree.': 'Cada emparejamiento y cada discrepancia deben referirse a filas reales, ninguna fila puede emparejarse dos veces y los importes emparejados tienen que coincidir.',
    'Evaluation suite includes robustness/metamorphic cases': 'El conjunto de evaluación incluye casos de robustez y metamórficos',
    'Your evaluation must include robustness categories and metamorphic transformations, not only happy-path cases.': 'Tu evaluación tiene que incluir categorías de robustez y transformaciones metamórficas, no solo casos del camino feliz.',
    'Release/rollback/runbook complete': 'La publicación, la marcha atrás y el runbook están completos',
    'Release manifest, rollback criteria and drill, and a runbook with owner, kill switch and rollback steps.': 'Manifiesto de versión, criterios y simulacro de marcha atrás, y un runbook con responsable, interruptor de emergencia y pasos para dar marcha atrás.',
    'Validation evidence tied to MOEs': 'La evidencia de validación está ligada a las MOE',
    'Each validation scenario names the MOE it measures and the measured result.': 'Cada escenario de validación nombra la MOE que mide y el resultado medido.',
    'DEFINE review': 'Revisión DEFINIR',
    'RESEARCH review': 'Revisión INVESTIGAR',
    'ARCHITECT review': 'Revisión ARQUITECTURA',
    'CREATE review': 'Revisión CONSTRUIR',
    'VERIFY review': 'Revisión VERIFICAR',
    'SECURITY review': 'Revisión SEGURIDAD',
    'IMPROVE review': 'Revisión MEJORAR',
    'RELEASE review': 'Revisión PUBLICAR',
    'VALIDATE review': 'Revisión VALIDAR',
})
